import torch
import torch.nn as nn
import torch.nn.functional as F

# ============================================================
# 1. Architecture Definition: Nomadic Resonance v2.0
# ============================================================

class PrimalExpert(nn.Module):
    """
    A protoplasmic neural network with no fixed structure.
    It receives its geometry (Weights) dynamically from the Hypernet.
    """
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim

    def forward(self, x, weights):
        # Dynamically inject weights generated by the Hypernetwork (Functional API)
        x = F.linear(x, weights['w1'], weights['b1'])
        x = torch.tanh(x)
        x = F.linear(x, weights['w2'], weights['b2'])
        return x

class NomadicHyperNet(nn.Module):
    """
    The 'Command Center' that translates the Will to Resonance (Phi) 
    into weight geometry.
    """
    def __init__(self, latent_dim, target_shapes):
        super().__init__()
        self.shapes = target_shapes
        total_params = sum(p.numel() for p in target_shapes.values())
        self.net = nn.Sequential(
            nn.Linear(latent_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, total_params)
        )

    def forward(self, z):
        flat_params = self.net(z)
        params = {}
        start = 0
        for name, shape in self.shapes.items():
            end = start + shape.numel()
            params[name] = flat_params[0, start:end].view(shape) # Batch dimension handling
            start = end
        return params

class ResonanceEngine(nn.Module):
    def __init__(self, input_dim=1, hidden_dim=16, output_dim=1):
        super().__init__()
        self.expert = PrimalExpert(input_dim, hidden_dim, output_dim)
        
        # Define the target weight shapes for the PrimalExpert
        self.target_shapes = {
            'w1': torch.Size([hidden_dim, input_dim]),
            'b1': torch.Size([hidden_dim]),
            'w2': torch.Size([output_dim, hidden_dim]),
            'b2': torch.Size([output_dim])
        }
        
        self.hypernet = NomadicHyperNet(latent_dim=2, target_shapes=self.target_shapes)
        
        # Latent space for preserving identity (The core of Phi)
        self.z = nn.Parameter(torch.randn(1, 2)) 
        self.stress_energy = 0.0 # Accumulated delta_x (Energy)
        self.tau_k_barrier = 1.5 # Threshold energy for Separatrix Collapse
        self.prev_weights = None

    def forward(self, x):
        weights = self.hypernet(self.z)
        return self.expert(x, weights), weights

    def check_collapse(self):
        """
        Separatrix Collapse: Structural transition when energy exceeds the barrier.
        Triggers a jump in the latent space.
        """
        if self.stress_energy > self.tau_k_barrier:
            with torch.no_grad():
                # Nomadic Jump: Destroying the current topology to find a new resonance
                self.z.add_(torch.randn_like(self.z) * 2.0) 
            self.stress_energy = 0.0 # Reset energy after collapse
            return True
        return False

# ============================================================
# 2. Execution: Training Loop & Environment Simulation
# ============================================================

def main():
    print("="*60)
    print(" [Nomadic Resonance v2.0] Engine Initialized")
    print(" Principle: Structural Adaptation via Dynamic Morphing")
    print("="*60)

    model = ResonanceEngine()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    
    epochs = 300
    x_train = torch.linspace(-3, 3, 100).unsqueeze(1)
    
    for epoch in range(epochs):
        # --- Paradigm Shift Simulation ---
        if epoch < 100:
            y_true = x_train * 1.5
            env_name = "Regime A (Linear)"
        elif epoch < 200:
            # Sudden non-linear shift (Triggers delta_x surge)
            y_true = torch.sin(x_train * 2.0) * 2.0
            env_name = "Regime B (Non-linear)"
        else:
            # Paradigm reversal
            y_true = torch.cos(x_train * 3.0) * -2.0
            env_name = "Regime C (Phase-shifted)"

        # --- 1. Forward Pass & Delta x Calculation ---
        model.train()
        optimizer.zero_grad()
        
        y_pred, current_weights = model(x_train)
        delta_x = F.mse_loss(y_pred, y_true)
        
        # --- 2. Stress Energy Accumulation & Collapse Check ---
        model.stress_energy += delta_x.item()
        collapsed = model.check_collapse()
        
        if collapsed:
            print(f"\n[💥 STRUCTURAL COLLAPSE DETECTED!] Epoch {epoch} | Env: {env_name}")
            print(f" -> Energy exceeded the Tau_k barrier. Forcing a topological transition.")
            # Reset optimizer momentum to break away from past inertia
            optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
            model.prev_weights = None
            continue 

        # --- 3. Topological Loss: L_topo = L_sync + alpha * L_dogma ---
        l_sync = delta_x # Minimize integration latency
        l_dogma = torch.tensor(0.0)
        
        if model.prev_weights is not None:
            # Measure weight change (dW)
            current_w_flat = torch.cat([w.view(-1) for w in current_weights.values()])
            prev_w_flat = torch.cat([pw.view(-1) for pw in model.prev_weights.values()])
            dw = torch.norm(current_w_flat - prev_w_flat)
            
            # Dogma Penalty: If delta_x is high but dW is low, penalize rigidity
            l_dogma = F.relu((delta_x / (dw + 1e-6)) - 1.0) * 0.1
            
        loss = l_sync + l_dogma
        loss.backward()
        optimizer.step()
        
        model.prev_weights = {k: v.detach() for k, v in current_weights.items()}
        
        if epoch % 20 == 0:
            print(f"Epoch {epoch:03d} | {env_name:20s} | Delta x: {delta_x.item():.4f} | Stress: {model.stress_energy:.4f} | Dogma Pen: {l_dogma.item():.4f}")

    print("\n[Simulation Finished] The Nomadic Intelligence survived through paradigm shifts.")

if __name__ == "__main__":
    main()